Repository HEIGE-PCloud/DoIt, pull requests merged in 2021-10, with the labels that each got.

#260 feat: enhance searching experience
  exampleSite/config.toml
  layouts/index.json
Labels: enhancement

#258 feat: enable commentCount for Twikoo and Waline
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  i18n/en.toml
  i18n/zh-CN.toml
  layouts/partials/comment.html
  layouts/posts/single.html
  src/js/theme.js
Labels: enhancement, dependencies

#262 feat: match the theme-color meta with header color
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  layouts/_default/baseof.html
  layouts/partials/head/meta.html
  src/js/theme.js
Labels: enhancement

#312 fix: cookieconsent
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  layouts/partials/assets.html
  src/js/theme.js
Labels: bug, dependencies, pjax

#318 i18n: fix typo for pt-BR translation
  i18n/pt-BR.toml
Labels: translation

#311 fix: handle empty fields in friend shortcode properly
  assets/css/_partial/_single/_friend.scss
  assets/js/theme.min.js.map
  exampleSite/content/posts/tests/friend-link-tests/index.en.md
  exampleSite/resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  layouts/shortcodes/friend.html
Labels: bug, shortcode
