Repository HEIGE-PCloud/DoIt, pull requests merged in 2021-11, with the labels that each got.

#325 feat: add edit this page link
  assets/css/_partial/_single/_footer.scss
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  exampleSite/resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  i18n/en.toml
  i18n/zh-CN.toml
  layouts/partials/single/footer.html
  layouts/shortcodes/friend.html
Labels: new feature

#340 fix: prevent toc being resized unexpectedly
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  package-lock.json
  src/js/theme.js
Labels: bug

#351 feat: add license front matter support
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  layouts/posts/single.html
Labels: new feature

#356 docs: add docs on how to update the submodule
  README.md
  README.zh-cn.md
Labels: documentation

#360 fix: destroy lg instance at pjax:send
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  src/js/theme.js
Labels: bug
