Repository HEIGE-PCloud/DoIt, pull requests merged in 2021-12, with the labels that each got.

#375 chore: add eslint for theme.js and unify code style
  .eslintrc.yml
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/sw.min.js
  assets/sw.min.js.map
  package-lock.json
  package.json
  src/js/sw.js
  src/js/theme.js
Labels: enhancement

#379 feat: add Cloudflare analytics
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/partials/plugin/analytics.html
Labels: new feature

#393 add diaspora* social network
  assets/data/social.yml
  assets/js/theme.min.js.map
  exampleSite/config.toml
  package-lock.json
Labels: new feature

#391 refactor: migrate theme.js to js.build
  .babelrc
  assets/js/lib/katex.js
  assets/js/lib/twemoji.js
  assets/js/lib/twikoo.js
  assets/js/shims/katex.js
  assets/js/shims/twemoji.js
  assets/js/shims/twikoo.js
  assets/js/sw.js
  assets/js/theme.js
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/sw.min.js
  assets/sw.min.js.map
  exampleSite/assets/jsconfig.json
  exampleSite/content/posts/theme-documentation-built-in-shortcodes/index.en.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes/index.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/comment.html
  layouts/partials/head/link.html
  layouts/partials/plugin/script.html
  layouts/partials/scratch/configScript.html
  package-lock.json
  package.json
  src/lib/lunr.segmentit.js
Labels: enhancement

#395 refactor: keep improving `theme.js`
  assets/js/lib/cookieconsent.js
  assets/js/lib/echarts.js
  assets/js/lib/mermaid.js
  assets/js/shims/cookieconsent.js
  assets/js/shims/echarts.js
  assets/js/shims/mermaid.js
  assets/js/shims/mermaidAPI.js
  assets/js/theme.js
  layouts/partials/assets.html
  package-lock.json
  package.json
Labels: enhancement

#402 optimize: improve toc performance
  assets/js/theme.js
Labels: performance

#404 Update es.toml
  i18n/es.toml
Labels: translation

#406 feat: add aplayer shortcode
  assets/js/lib/aplayer.js
  assets/js/lib/echarts.js
  assets/js/shims/aplayer.js
  assets/js/theme.js
  exampleSite/content/posts/tests/aplayer-tests/index.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.zh-cn.md
  layouts/partials/assets.html
  layouts/shortcodes/aplayer.html
  layouts/shortcodes/audio.html
  package-lock.json
  package.json
Labels: new feature

#410 add Hosted on
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  i18n/en.toml
  i18n/es.toml
  i18n/zh-CN.toml
  layouts/partials/footer.html
Labels: new feature

#412 Update docs for linkToSource and linkToReport
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
Labels: documentation

#417 refactor: separate comment systems
  assets/js/lib/cookieconsent.js
  assets/js/lib/giscus.js
  assets/js/lib/gitalk.js
  assets/js/lib/katex.js
  assets/js/lib/remark42.js
  assets/js/lib/twemoji.js
  assets/js/lib/twikoo.js
  assets/js/lib/utterances.js
  assets/js/lib/valine.js
  assets/js/lib/vssue.js
  assets/js/lib/waline.js
  assets/js/shims/valine.js
  assets/js/shims/waline.js
  assets/js/theme.js
  layouts/partials/comment.html
  package-lock.json
  package.json
Labels: enhancement

#418 refactor: add topbar to package.json
  assets/js/shims/topbar.js
  assets/js/theme.js
  layouts/partials/assets.html
  package-lock.json
  package.json
Labels: enhancement

#425 refactor: use Hugo render hooks for header link rendering
  .gitignore
  assets/js/theme.js
  exampleSite/resources/_gen/assets/scss/css/2f1ef0.scss_dd6b28f8de2423d755b68db23d9ed063.content
  exampleSite/resources/_gen/assets/scss/css/2f1ef0.scss_dd6b28f8de2423d755b68db23d9ed063.json
  exampleSite/resources/_gen/assets/scss/css/790698.scss_e6be5577c95b33ef41b4c8ab355ec8c5.content
  exampleSite/resources/_gen/assets/scss/css/790698.scss_e6be5577c95b33ef41b4c8ab355ec8c5.json
  exampleSite/resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  exampleSite/resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.json
  exampleSite/resources/_gen/assets/scss/lib/aplayer/dark.scss_be0d6bec1a51ff037db8cc74d6ec1271.content
  exampleSite/resources/_gen/assets/scss/lib/aplayer/dark.scss_be0d6bec1a51ff037db8cc74d6ec1271.json
  exampleSite/resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.content
  exampleSite/resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.json
  layouts/_default/_markup/render-heading.html
Labels: enhancement

#426 refactor: optimize toc logic
  assets/css/_core/_media.scss
  assets/css/_partial/_single/_toc.scss
  assets/js/theme.js
  layouts/posts/single.html
Labels: enhancement

#430 [pt-BR] feat: add hosted on
  i18n/pt-BR.toml
Labels: translation

#428 fix: destroy all aplayer instances on pjax:send
  assets/js/lib/aplayer.js
  layouts/partials/assets.html
  layouts/shortcodes/aplayer.html
Labels: bug
