Repository HEIGE-PCloud/DoIt, pull requests merged in 2021-05, with the labels that each got.

#36 [FIX] Mermaid
  assets/data/cdn/jsdelivr.yml
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/mermaid/mermaid.min.js
  assets/lib/mermaid/mermaid.scss
  exampleSite/content/posts/tests/mermaid-tests/index.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.zh-cn.md
  src/js/theme.js
Labels: bug, dependencies, documentation

#37 Delete Instagram related SCSS and docs
  assets/css/_page/_single.scss
  assets/css/_partial/_single/_instagram.scss
  exampleSite/content/posts/tests/builtin-shortcodes-tests/index.en.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes/index.en.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes/index.zh-cn.md
Labels: dependencies, documentation

#35 [FEATURE] Add `pageStyle` option
  assets/css/_core/_media.scss
  assets/css/_page/_index.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  layouts/posts/single.html
  src/js/theme.js
Labels: documentation, enhancement

#38 [FEATURE] Add PWA support to documentation site
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/offline/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/static/site.webmanifest
  exampleSite/static/sw.min.js
  exampleSite/static/sw.min.js.map
  layouts/_default/baseof.html
  layouts/partials/footer.html
  layouts/partials/head/meta.html
  package.json
  src/js/sw.js
  src/js/theme.js
Labels: enhancement

#42 [FIX] Check if content is empty before passing
  layouts/partials/function/content.html
Labels: bug

#66 chore(update-libs): update waline
  assets/data/cdn/jsdelivr.yml
  assets/lib/VERSION
  assets/lib/waline/Waline.min.js
Labels: dependencies

#80 [FIX] Add descriptive label to links
  exampleSite/resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  layouts/_default/summary.html
Labels: enhancement

#86 feat: add ORCID under social links on home page
  assets/data/social.yml
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
Labels: enhancement
