Repository HEIGE-PCloud/DoIt, pull requests merged in 2022-01, with the labels that each got.

#432 [Feature] Sort table
  assets/css/_page/_single.scss
  assets/data/cdn/jsdelivr.yml
  assets/js/shims/tablesort.js
  assets/js/theme.js
  assets/lib/VERSION
  assets/lib/tablesort/tablesort.min.js
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  layouts/partials/assets.html
  package-lock.json
  package.json
Labels: new feature

#443 fix: telegram comment style
  layouts/partials/comment.html
Labels: bug

#446 fix: remove incorrect keepstatic logic
  layouts/posts/single.html
  resources/_gen/assets/scss/css/2f1ef0.scss_dd6b28f8de2423d755b68db23d9ed063.content
  resources/_gen/assets/scss/css/2f1ef0.scss_dd6b28f8de2423d755b68db23d9ed063.json
  resources/_gen/assets/scss/css/790698.scss_e6be5577c95b33ef41b4c8ab355ec8c5.content
  resources/_gen/assets/scss/css/790698.scss_e6be5577c95b33ef41b4c8ab355ec8c5.json
  resources/_gen/assets/scss/css/f79aa6.scss_19472c45f72842db329f68de46e6b738.content
  resources/_gen/assets/scss/css/f79aa6.scss_19472c45f72842db329f68de46e6b738.json
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.json
  resources/_gen/assets/scss/lib/aplayer/dark.scss_be0d6bec1a51ff037db8cc74d6ec1271.content
  resources/_gen/assets/scss/lib/aplayer/dark.scss_be0d6bec1a51ff037db8cc74d6ec1271.json
  resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.content
  resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.json
  resources/_gen/assets/scss/lib/waline/waline.scss_0cdef61725905fb7b816627b546f44b8.content
  resources/_gen/assets/scss/lib/waline/waline.scss_0cdef61725905fb7b816627b546f44b8.json
Labels: bug

#455 feat: enhance support for custom library JS and CSS
  exampleSite/config.toml
  exampleSite/content/posts/tests/aplayer-tests/index.en.md
  exampleSite/content/posts/tests/author-fallback-tests/index.en.md
  exampleSite/content/posts/tests/author-single-tests/index.en.md
  exampleSite/content/posts/tests/bilibili-tests/index.en.md
  exampleSite/content/posts/tests/builtin-shortcodes-tests/index.en.md
  exampleSite/content/posts/tests/echarts-tests/index.en.md
  exampleSite/content/posts/tests/extend-shortcodes-tests/index.en.md
  exampleSite/content/posts/tests/friend-link-tests/index.en.md
  exampleSite/content/posts/tests/katex-tests/index.en.md
  exampleSite/content/posts/tests/mapbox-tests/index.en.md
  exampleSite/content/posts/tests/markdown-tests/index.en.md
  exampleSite/content/posts/tests/mermaid-tests/index.en.md
  exampleSite/content/posts/tests/music-tests/index.en.md
  exampleSite/content/posts/tests/series-taxonomy-tests/index.en.md
  exampleSite/content/posts/tests/series-taxonomy-tests/index.zh-cn.md
  exampleSite/content/posts/tests/showcase-tests/index.en.md
  exampleSite/content/posts/tests/toc-tests/index.en.md
  exampleSite/content/posts/tests/typeit-tests/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/head/link.html
  layouts/partials/plugin/defer-style.html
  layouts/partials/plugin/style.html
  package.json
Labels: enhancement
